name: foehnfirecorr
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.8
  - jupyterlab
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - geopy
  - pip
  - cookiecutter
  - xlrd
  - pip:
    - kedro
    - kedro-viz
    - openpyxl

# Need to install "dypy" manually for fire map plotting (due to broken installation command)
