name: foehnfireenv
channels:
  - defaults
dependencies:
  - python==3.8
  - jupyterlab
  - ipython==7.10.0 # Due to iPython issue
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - geopy
  - pip
  - xlrd
  - cartopy
  - netcdf4
  - pip:
    - kedro==0.17.3
    - kedro-viz
    - openpyxl
    - geopandas
    - mlflow
    - pytest
    - pytest-cov
    - plotly
    - xgboost
    - causalnex
