name: foehnfirecorrplot
channels:
  - defaults
dependencies:
  - python==3.8
  - jupyterlab
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - geopy
  - pip
  - xlrd
  - cartopy
  - netcdf4
#  - geopandas
  - pip:
    - kedro
    - kedro-viz
    - openpyxl
    - geopandas
    - mlflow
    - pytest
    - pytest-cov
#    - xgboost
#    - causalnex

# Need to install "dypy" manually for fire map plotting (due to broken installation command)
